//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryID
    {
        public int IDSalary { get; set; }
        public string Salary { get; set; }
        public string IDTeacher { get; set; }
    }
}
