//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectID
    {
        public int IDSubjects { get; set; }
        public string Subject { get; set; }
        public string Teacher { get; set; }
    }
}
