//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherID
    {
        public int IDTeacher { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string IDGroup { get; set; }
    }
}
